### PR TITLE
Re-create 1161-E.118 documents (En, Fr, Es)

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
*As requested in https://github.com/ituob/service-publications-docs/issues/1*

Note: the language of the country names contained in the YAML file is English only. The other languages are missing.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@manuel489 can you help obtain the other country names of other languages from existing ITU documents? Thanks.

**Comment by ronaldtse** [comment]
Thank you @manuel489 !

**Comment by manuelfuenmayor** [comment]
> @manuel489 can you help obtain the other country names of other languages from existing ITU documents? Thanks.

Oh, I was about to attend to your query. Sorry I didn't reply earlier.
I'll push another PR for it 👍

**Comment by ronaldtse** [comment]
Thanks @manuel489 !

**Pull request merged**
