### PR TITLE
Re-create 1000-SR.1 service publication document

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
*As requested in https://github.com/ituob/service-publications-docs/issues/1*

### CODE REVIEW

**Comment by manuelfuenmayor** [comment]
Hey @ronaldtse,

I have added the first document using YAML data.
I draw your attention to some formatting differences in comparison to the "old" version of the document.

1. The `no_collect_calls` restrictions are shown one by one in separate paragraphs instead of one paragraph:

*"Old" version*:

Cap1_original


*"New version" (with YAML data)*:

Cap1_recreated

Also, there is paragraph separation instead of line-breaks.


2. The position of the data is not always the same as the "old" version. By convention, I have placed the `notes` field in last position. In contrast to the "old" version that sometimes it is placed at the end and sometimes not.

*"Old" version*:
Cap2_old


*"New version" (with YAML data)*:
Cap2_new


Do these differences matter?

**Comment by ronaldtse** [comment]
@manuel489 these differences are acceptable. It is possible to use Liquid syntax to further tailor the sentences in issue 1, but it may not be necessary. This looks really good. Thanks!

**Comment by ronaldtse** [comment]
@manuel489 if these are the only differences, we can merge it. Thanks!

**Comment by manuelfuenmayor** [comment]
> @manuel489 if these are the only differences, we can merge it. Thanks!

Ok, I'm merging this first document (1000-SR.1) for us to have in master branch. I will follow with the rest in another PR. Thanks!

**Pull request merged**
